# Generated by Django 5.2.4 on 2025-08-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="station.order",
            ),
        ),
    ]
