# Generated by Django 5.2.4 on 2025-08-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_alter_ticket_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["cargo", "seat"]},
        ),
        migrations.AlterField(
            model_name="ticket",
            name="journey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="station.journey",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("journey", "cargo", "seat")},
        ),
    ]
