# Generated by Django 5.2.4 on 2025-08-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_alter_ticket_options_alter_ticket_journey_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="traintype",
            options={"verbose_name_plural": "train_types"},
        ),
        migrations.AlterField(
            model_name="train",
            name="train_type",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="station.traintype",
            ),
        ),
    ]
