# Generated by Django 5.2.4 on 2025-08-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0004_alter_traintype_options_alter_train_train_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="traintype",
            options={"verbose_name_plural": "train_type"},
        ),
        migrations.AlterField(
            model_name="train",
            name="train_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="station.traintype",
            ),
        ),
    ]
